### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by Majed6**
Update Opentracing to the latest release

### CODE REVIEW

**Comment by Majed6** [comment]
Updated the docs as well.

**Comment by jukylin** [comment]
I would like to continue supporting php5.6

**Comment by Majed6** [comment]
I appreciate that but [opentracing-php](https://github.com/opentracing/opentracing-php) has dropped support for php5.6 . I was interested in upgrading opentracing to the latest release :)

**Comment by jukylin** [comment]
In fact, I'm also confused.some people or company still using the php5.6. I don't want to abandon them.

**Comment by cawolf** [comment]
Does that mean that you do not intent to upgrade further than `opentracing/opentracing:1.0.0-beta5`, as this is the last version supporting PHP 5.6? If so, we will need to choose another tracer or fork this repository and maintain that, as we want to move to a stable opentracing release.

**Comment by jukylin** [comment]
> Does that mean that you do not intent to upgrade further than `opentracing/opentracing:1.0.0-beta5`, as this is the last version supporting PHP 5.6? If so, we will need to choose another tracer or fork this repository and maintain that, as we want to move to a stable opentracing release.

I have a plan.  create new version v3.0 that support the latest `opentracing/opentracing`, not support php 5.6 again.
Are you interested?

**Comment by cawolf** [comment]
Yes, I am interested in that, sounds like a good plan to me. Do you want to maintain a separate 2.x branch and maintain both versions? And do you need any help?

**Comment by jukylin** [comment]
> Yes, I am interested in that, sounds like a good plan to me. Do you want to maintain a separate 2.x branch and maintain both versions? And do you need any help?

Only fix bug not add new feature. If you interested, I'm going to start in August.

**Comment by cawolf** [comment]
I'm looking forward to it. :+1:

**Comment by jukylin** [comment]
Sorry, this month is too busy.Mey be you can follow [opentelemetry-php](https://github.com/open-telemetry/opentelemetry-php).

**Comment by cawolf** [comment]
> Sorry, this month is too busy.Mey be you can follow [opentelemetry-php](https://github.com/open-telemetry/opentelemetry-php).

No problem. Do you still want to implement the newer version branch? 

opentelemetry is currently not in a useful production state, and may be in the future. However, as it merges opentracing and opencensus, it would be beneficial if this library would implement the stable opentracing release, which we are trying to release.

**Comment by jukylin** [comment]
We are working [dev_v3](https://github.com/jukylin/jaeger-php/tree/dev_v3)

**Pull request closed without merging**
