### PR TITLE
fix：Header header compatibility fix

### PR DESCRIPTION
**Pull request by gitsrc**
Remote call, header header field will change, compatibility fix

### CODE REVIEW

**Comment by jukylin** [comment]
What call do you use?

**Comment by gitsrc** [comment]
The lnmp server calls another php server. The fields in the header in the $_SERVER variable will change to the HTTP_ style, which will not be correct.

**Comment by gitsrc** [comment]
Increase compatibility by converting field names in the $_SERVER variable

**Comment by jukylin** [comment]
I think it should not be in the method

**Pull request closed without merging**
