### PR TITLE
Fix issue #18

### LINKED ISSUE #18: bad trace id conversion
https://github.com/jukylin/jaeger-php/blob/master/src/Jaeger/SpanContext.php#L79

I think that it should be 16 instead of 15 here or it ends up with `<trace-without-root-span>` in jaeger

### PR DESCRIPTION
**Pull request by pantrif**
I don't think that we need all these checks here. 
This seems to resolve #18 .

### CODE REVIEW

**Comment by jukylin** [comment]
It not only support call between php and php,I want to support php and [golang](https://github.com/jaegertracing/jaeger-client-go/blob/master/context.go#L249), and so on.

**Comment by jukylin** [comment]
I made a mistake，is [TraceIDFromString](https://github.com/jaegertracing/jaeger-client-go/blob/master/context.go#L216) not [SpanIDFromString](https://github.com/jaegertracing/jaeger-client-go/blob/master/context.go#L249)

**Comment by jukylin** [comment]
I fix this problem.you can chenckout branch ```fix_traceid_len``` to test.

**Comment by pantrif** [comment]
Yes it works as expected now. Thanks!

**Comment by jukylin** [comment]
Done in [PR 20](https://github.com/jukylin/jaeger-php/pull/20)

**Pull request closed without merging**
